export default [
    {
        id:1,
        name:'Programing',
        icon:'/coding.png',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/health.png',
        prompt:''
    },
    {
        id:3,
        name:'Creative',
        icon:'/creative.png',
        prompt:''
    },
]